addresses:
    type:       rest
    resource:   ProjectBundle\Controller\AddressesController
    
homepage:
    path: /{_locale}
    requirements:
        _locale: '%app_locales%'
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    default/homepage.html.twig
        _locale:     '%locale%'